#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfsgluster
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsgluster
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 12.0.2.8
    path: "/myvolume"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8spod2nfsgluster
  labels:
    app: k8spod2nfsgluster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8spod2nfsgluster
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: k8spod2nfsgluster
    spec:
      containers:
      - image: javiermugueta/k8spod2nfsgluster
        ports:
        - containerPort: 80
          name: k8spod2nfsgluster
        #command:
        #  - sh
        #  - -c
        #  - 'while true; do date >> /usr/share/nginx/html/index.html; hostname >> /usr/share/nginx/html/index.html; sleep 30; done;'
        imagePullPolicy: IfNotPresent
        name: k8snfspod
        volumeMounts:
          - name: nfsgluster
            mountPath: "/usr/share/nginx/html"
      volumes:
      - name: nfsgluster
        persistentVolumeClaim:
          claimName: nfsgluster
---
apiVersion: v1
kind: Service
metadata:
  name: k8spod2nfsgluster
spec:
 type: LoadBalancer
 selector:
  app: k8spod2nfsgluster
 ports:
   - name: client
     protocol: TCP
     port: 80