#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfsgluster
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsgluster
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 12.0.2.7
    path: "/myvolume"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8spod2nfsgfs
  labels:
    app: k8spod2nfsgfs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8spod2nfsgfs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: k8spod2nfsgfs
    spec:
      hostAliases:
      - ip: "12.0.2.7"
        hostnames:
        - "gfs01"
      - ip: "12.0.2.8"
        hostnames:
        - "gfs02"
      - ip: "12.0.2.9"
        hostnames:
        - "gfs03"
      containers:
      - image: nginx
        ports:
        - containerPort: 80
          name: k8spod2nfsgfs
        imagePullPolicy: IfNotPresent
        name: k8snfspod
        volumeMounts:
          - name: nfsgluster
            mountPath: "/usr/share/nginx/html"
      volumes:
      - name: nfsgluster
        persistentVolumeClaim:
          claimName: nfsgluster
